'use strict';
(() => {
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=v=>Math.max(0,Math.min(1,v)),range=(p,a,b)=>clamp((p-a)/(b-a)),smooth=v=>v*v*(3-2*v);
const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');let reduced=reducedQuery.matches;
const motion={demoDuration:42,cues:{'unscrew-start':.10,'internal-reveal':.32,'mist-burst':.52,'reassembly-lock':.91}};
const scenes=$$('.scroll-scene'),chapters=$$('[data-chapter]'),railLinks=$$('.chapter-rail>a');
const header=$('.header'),pageProgress=$('.page-progress'),railProgress=$('.rail-track i');
const menuButton=$('.menu-button'),menu=$('#menu');
const setMenu=open=>{menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'أغلق القائمة':'افتح القائمة');document.body.style.overflow=open?'hidden':'';if(open)$('a',menu).focus();};
menuButton.addEventListener('click',()=>setMenu(menu.hidden));menu.addEventListener('click',e=>{if(e.target.closest('a'))setMenu(false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){setMenu(false);menuButton.focus();}if(e.key==='Tab'&&!menu.hidden){const links=$$('a',menu),first=links[0],last=links.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();menuButton.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();menuButton.focus();}else if(document.activeElement===menuButton){e.preventDefault();(e.shiftKey?last:first).focus();}}});
const steps=[{image:'assets/anatomy.webp',alt:'الفوّاحة المفتوحة وقطعة اللباد'},{image:'assets/scent.webp',alt:'رذاذ العطر على قطعة اللباد'},{image:'assets/hero.webp',alt:'الفوّاحة المغلقة معلّقة على سبحة صمد'}];
const ritualButtons=$$('.ritual-step'),ritualImage=$('#ritual-image');let currentStep=0;
function setStep(i){if(i===currentStep)return;currentStep=i;ritualButtons.forEach((el,n)=>{el.classList.toggle('active',n===i);el.setAttribute('aria-pressed',String(n===i));$('.step-mark',el).textContent=n===i?'−':'+';});ritualImage.src=steps[i].image;ritualImage.alt=steps[i].alt;$('.photo-index').textContent=`0${i+1} / 03`;}
ritualButtons.forEach(button=>button.addEventListener('click',()=>setStep(Number(button.dataset.step))));
const canvas=$('#color-field'),ctx=canvas.getContext('2d');let cw=0,ch=0,colorProgress=0,accent='#20b1c2',colorClosed=false;
const palette=['#20b1c2','#859d30','#d9a637','#cb6181','#7a374b','#425d96','#7c529b','#526652'];
let seed=43;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};
const particles=Array.from({length:160},(_,i)=>({a:random()*Math.PI*2,r:.24+random()*.45,z:.4+random()*1.5,rotation:random()*Math.PI,color:palette[i%8],size:1.5+random()*4}));
const padSprite=new Image();padSprite.src='assets/components.webp';padSprite.onload=()=>paint();
function paint(){if(!ctx)return;ctx.clearRect(0,0,cw,ch);const p=reduced?.42:colorProgress,blast=Math.sin(range(p,.1,.95)*Math.PI),spiral=range(p,.1,.85)*2.4,n=cw<650?65:particles.length;for(let i=0;i<n;i++){const item=particles[i],a=item.a+spiral*(i%2?1:-1)*.55,radius=item.r*(.6+blast*1.1),x=cw*.34+Math.cos(a)*cw*radius*item.z,y=ch*.49+Math.sin(a)*ch*radius*item.z;ctx.save();ctx.translate(x,y);ctx.rotate(item.rotation+p*(i%2?3:-3));ctx.globalAlpha=x>cw*.53&&y>ch*.2&&y<ch*.75?.08:.14+item.z*.23;const size=item.size*(1+blast*3)*(cw<650?.6:1);if(i%7===0&&padSprite.complete&&padSprite.naturalWidth){ctx.filter=`hue-rotate(${i*41%300}deg)`;ctx.drawImage(padSprite,1186,350,237,497,-size,-size*2,size*2,size*4);}else{ctx.fillStyle=i%4===0?accent:item.color;ctx.beginPath();ctx.arc(0,0,size*.36,0,Math.PI*2);ctx.fill();}ctx.restore();}}
function sizeCanvas(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);cw=box.width;ch=box.height;canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);ctx?.setTransform(dpr,0,0,dpr,0,0);paint();}
const canvasObserver=new ResizeObserver(sizeCanvas);canvasObserver.observe(canvas);
const colorProduct=$('.color-product'),colorPad=$('.color-assembly .part-pad'),colorCap=$('.color-assembly .part-cap'),previewButton=$('.preview-close');
function updateColorPose(){colorPad.style.transform=colorClosed?'translateY(0px)':'translateY(-225px)';colorCap.style.transform=colorClosed?'translateY(29px) rotateY(360deg)':'translateY(-205px) rotateY(0deg)';previewButton.setAttribute('aria-pressed',String(colorClosed));previewButton.textContent=colorClosed?'شاهد اللون بالداخل':'شاهدها مغلقة';}
previewButton.addEventListener('click',()=>{colorClosed=!colorClosed;updateColorPose();});
$$('.swatches button').forEach(button=>button.addEventListener('click',()=>{accent=button.dataset.color;$$('.swatches button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('.color-name').textContent=button.dataset.name;const filter=button.dataset.name==='أسود'?'grayscale(1) brightness(.28)':`hue-rotate(${button.dataset.hue}deg) saturate(${button.dataset.name==='عنّابي'?.7:1.15}) brightness(${button.dataset.name==='عنّابي'?.55:1})`;$('#colors').style.setProperty('--accent',accent);$('#colors').style.setProperty('--pad-filter',filter);colorProduct.setAttribute('aria-label',`معاينة الفوّاحة مع اللباد: ${button.dataset.name}`);if(colorClosed){colorClosed=false;updateColorPose();}paint();}));
const els={heroMedia:$('.hero-media'),heroCopy:$('.hero-copy'),heroCaption:$('.hero-caption'),heroBottom:$('.hero-bottom'),scene:$('.mechanism-scene'),cap:$('.mechanism-frame .part-cap'),pad:$('.mechanism-frame .part-pad'),spray:$('.scent-reveal'),caption:$('.mechanism-step'),captionText:$('.mechanism-caption p'),readout:$('.readout-number'),anatomyBar:$('.anatomy-progress i'),colorCopy:$('.color-copy'),giftMedia:$('.gift-media'),giftCopy:$('.gift-copy'),quote:$('.quote-section p')};
const mist=$('.scent-cloud');for(let i=0;i<100;i++){const dot=document.createElement('i');dot.dataset.angle=(random()-.5)*1.8;dot.dataset.offset=random();mist.append(dot);}const droplets=$$('i',mist);

const nfcCard=$('.nfc-card'),nfcNotification=$('.phone-notification'),nfcMessage=$('.phone-message'),nfcIdle=$('.phone-idle'),nfcSteps=$$('.nfc-steps span');let nfcManual=false,nfcFrame=0;
function applyNfc(p){if(nfcManual)return;renderNfc(p);}
function renderNfc(p){const flip=smooth(range(p,0,.3)),approach=smooth(range(p,.3,.55)),message=smooth(range(p,.68,.85));nfcCard.style.transform='translate('+(-approach*30)+'%, '+(-approach*40)+'%) rotateY('+(flip*180)+'deg) rotateZ('+(-12+approach*16)+'deg) scale('+(1-approach*.12)+')';nfcCard.style.opacity=1-smooth(range(p,.6,.78))*.9;nfcNotification.style.opacity=smooth(range(p,.5,.61))*(1-message);nfcNotification.style.transform='translateY('+((1-smooth(range(p,.5,.61)))*-12)+'px)';nfcMessage.style.opacity=message;nfcMessage.style.transform='translateY('+((1-message)*18)+'px)';nfcIdle.style.opacity=1-message;$('.tap-rings').style.opacity=Math.sin(range(p,.48,.7)*Math.PI);nfcSteps.forEach((s,i)=>s.classList.toggle('active',i===(p<.5?0:p<.72?1:2)));}
$('.nfc-play').addEventListener('click',()=>{cancelAnimationFrame(nfcFrame);nfcManual=true;const start=performance.now();const tick=t=>{const p=clamp((t-start)/4200);renderNfc(reduced?1:p);if(p<1&&!reduced)nfcFrame=requestAnimationFrame(tick);else nfcManual=false;};nfcFrame=requestAnimationFrame(tick);});

const lights=new Map(scenes.map(el=>[el,$('.emerald-light',el)])),state=new Map();let phase=-1;
function setPhase(n){if(phase===n)return;phase=n;const captions=[['افتح الفوّاحة','لفّة تكشف التفاصيل.'],['مساحة لعطرك','قطعة لباد، وعطرك المفضّل.'],['رَشّة، تصنع الأثر','العطر يلامس النسيج ويصبح جزءًا من طقسك.'],['أغلق. واحتفظ بالأثر.','اللباد في الداخل. والفوّاحة ترافقك.']];els.caption.textContent=captions[n][0];els.captionText.textContent=captions[n][1];}
function applyScene(el,p){state.set(el.id,p);if(reduced)return;const light=lights.get(el);if(light){light.style.setProperty('--light-x',`${Math.sin(p*Math.PI*2)*7}%`);light.style.setProperty('--light-y',`${Math.cos(p*Math.PI)*5}%`);light.style.setProperty('--light-turn',`${p*25}deg`);}if(el.id==='home'){const q=smooth(range(p,.06,.95));els.heroMedia.style.transform=`scale(${1+q*.20}) translateX(${q*2}%)`;els.heroCopy.style.transform=`translateY(${-q*28}px)`;els.heroCopy.style.opacity=1-range(p,.63,.95)*.65;els.heroCaption.style.opacity=1-range(p,.45,.85);els.heroBottom.style.opacity=1-range(p,.5,.9);}
if(el.id==='anatomy'){const opening=smooth(range(p,.08,.27)),padOut=smooth(range(p,.22,.39)),closing=smooth(range(p,.74,.93)),capGap=opening*(1-closing),padGap=padOut*(1-smooth(range(p,.68,.81)));els.cap.style.transform=`translateY(${29-capGap*239}px) rotateY(${opening*720-closing*720}deg)`;els.pad.style.transform=`translateY(${-padGap*240}px)`;const sprayShow=smooth(range(p,.40,.47))*(1-smooth(range(p,.61,.68)));els.spray.style.opacity=sprayShow;els.spray.style.transform=`scale(${1.08-range(p,.4,.68)*.08})`;els.scene.style.opacity=1-sprayShow;els.pad.style.filter=`saturate(${1+range(p,.47,.58)*.65})`;els.pad.style.opacity=padGap>.03?1:.75;els.readout.textContent=String(Math.round(capGap*360)).padStart(3,'0')+'°';els.anatomyBar.style.transform=`scaleX(${p})`;setPhase(p<.24?0:p<.43?1:p<.67?2:3);const burst=range(p,.43,.62);droplets.forEach(dot=>{const travel=clamp((burst-Number(dot.dataset.offset)*.2)/.8);dot.style.transform=`translate(${travel*260}px,${Number(dot.dataset.angle)*travel*45}px) scale(${.35+travel*.5})`;dot.style.opacity=Math.sin(travel*Math.PI)*.22;});}
if(el.id==='colors'){colorProgress=p;els.colorCopy.style.transform=`translateY(${-Math.sin(p*Math.PI)*15}px)`;colorProduct.style.setProperty('--product-turn',`${Math.sin(p*Math.PI)*8}deg`);paint();}
if(el.id==='nfc')applyNfc(p);
if(el.id==='gift'){els.giftMedia.style.transform=`scale(${1.06-p*.06}) translateX(${p*1.2}%)`;els.giftCopy.style.transform=`translateY(${(1-smooth(p))*20}px)`;}}
let geometry=[],chapterGeometry=[],decorGeometry=[],totalHeight=1;const decor=[$('.ritual'),$('.quote-section')];
function measure(){geometry=scenes.map(el=>({el,start:el.offsetTop,range:Math.max(1,el.offsetHeight-$('.stage',el).offsetHeight)}));chapterGeometry=chapters.map(el=>({start:el.offsetTop,chapter:Number(el.dataset.chapter)}));decorGeometry=decor.map(el=>({el,start:el.offsetTop,height:el.offsetHeight,light:$('.emerald-light',el)}));totalHeight=Math.max(1,document.documentElement.scrollHeight-innerHeight);}
function updateAll(){const y=scrollY,p=clamp(y/totalHeight);header.classList.toggle('scrolled',y>45);pageProgress.style.transform=`scaleX(${p})`;railProgress.style.transform=`scaleY(${p})`;let active=0;chapterGeometry.forEach(g=>{if(g.start<y+innerHeight*.55)active=g.chapter;});railLinks.forEach((a,i)=>{a.classList.toggle('active',i===active);if(i===active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});if(!window.ScrollTrigger&&!reduced)geometry.forEach(g=>applyScene(g.el,clamp((y-g.start)/g.range)));if(!reduced)decorGeometry.forEach(g=>{const d=clamp((y+innerHeight-g.start)/(innerHeight+g.height));if(d<=0||d>=1)return;if(g.el.classList.contains('quote-section')){const q=smooth(range(d,.40,.80));els.quote.style.transform=`translateY(${-q*65}px) scale(${1+q*.07})`;els.quote.style.opacity=1-q;els.quote.style.filter=`blur(${q*9}px)`;}if(g.light)g.light.style.setProperty('--light-x',`${d*10-5}%`);});}
let queued=false;const onScroll=()=>{if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;updateAll();});}};addEventListener('scroll',onScroll,{passive:true});
let triggers=[];function configureMotion(){triggers.forEach(t=>t.kill());triggers=[];if(window.gsap&&window.ScrollTrigger&&!reduced){gsap.registerPlugin(ScrollTrigger);scenes.forEach(el=>triggers.push(ScrollTrigger.create({trigger:el,start:'top top',end:()=>`+=${Math.max(1,el.offsetHeight-$('.stage',el).offsetHeight)}`,invalidateOnRefresh:true,onUpdate:self=>applyScene(el,self.progress),onRefresh:self=>applyScene(el,self.progress)})));}if(reduced){renderNfc(1);els.heroCopy.style.opacity=1;els.heroMedia.style.transform='none';els.heroCopy.style.transform='none';els.heroCaption.style.opacity=1;els.heroBottom.style.opacity=1;els.scene.style.opacity=1;els.giftMedia.style.transform='none';els.giftCopy.style.transform='none';setPhase(1);}measure();updateAll();paint();}
configureMotion();addEventListener('resize',()=>{measure();updateAll();});document.fonts.ready.then(()=>{measure();window.ScrollTrigger?.refresh();updateAll();});addEventListener('load',()=>{measure();window.ScrollTrigger?.refresh();});reducedQuery.addEventListener('change',()=>{reduced=reducedQuery.matches;configureMotion();});
const params=new URLSearchParams(location.search);let demoRunning=false,demoStart=0,demoOffset=0,demoRaf=0;const demoButton=$('#demo-toggle'),duration=Math.min(180,Math.max(10,Number(params.get('duration'))||motion.demoDuration))*1000;
const stopDemo=()=>{demoRunning=false;cancelAnimationFrame(demoRaf);demoButton.textContent='تشغيل العرض';};
const playDemo=async()=>{if(demoRunning){stopDemo();return;}await document.fonts.ready;await Promise.all($$('img').map(img=>img.decode().catch(()=>{})));measure();demoOffset=.025+scrollY/totalHeight*.95;demoStart=performance.now();demoRunning=true;demoButton.textContent='إيقاف العرض';const tick=now=>{if(!demoRunning)return;const p=clamp(demoOffset+(now-demoStart)/duration);window.scrollTo({top:range(p,.025,.975)*totalHeight,behavior:'instant'});if(p>=1){stopDemo();return;}demoRaf=requestAnimationFrame(tick);};demoRaf=requestAnimationFrame(tick);};
const resetDemo=()=>{stopDemo();demoOffset=0;window.scrollTo({top:0,behavior:'instant'});scenes.forEach(el=>applyScene(el,0));window.ScrollTrigger?.update();};
if(params.get('demo')==='1'){$('.demo-bar').hidden=false;demoButton.addEventListener('click',playDemo);$('#demo-reset').addEventListener('click',resetDemo);document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Space'&&e.target===document.body){e.preventDefault();playDemo();}if(e.key.toLowerCase()==='r')resetDemo();});addEventListener('wheel',stopDemo,{passive:true});addEventListener('touchstart',stopDemo,{passive:true});}
addEventListener('pagehide',()=>{stopDemo();canvasObserver.disconnect();triggers.forEach(t=>t.kill());});
window.SAMD={motion,get states(){return Object.fromEntries(state);},get demoRunning(){return demoRunning;},resetDemo,playDemo};
})();
